name: aib
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Bicep:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Bicep folder
        uses: actions/checkout@v3
        with:
          repository: almalos/bicep
          ref: main
          path: bicep
        
      - name: 'Azure CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-azpssession: true

      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd     
      
      # - name: Create Azure Image Builder
      #   uses: azure/arm-deploy@v1
      #   with:
      #     scope: subscription
      #     region: westeurope
      #     template: bicep/aib.bicep
      #     parameters: parameters/aib.parameters.json
